[package]
name = "Server11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
enum-as-inner = "0.6.0"
dashmap = "5.5.3"